[build]
  # 构建命令
  command = "cd frontend && npm install && npm run build"
  # 发布目录
  publish = "frontend/dist"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

# 重定向配置，支持React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 缓存配置
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 